package com.inn.headstartdemo.audit;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
/**
 * 
 * @author Autogenerated by Headstart
 * @version 1.0
 *
 */

/**
 * Auditable annotation
 **/
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface Auditable
{
	/**
	 * 
	 * @return AuditActionType
	 */

	AuditActionType actionType();

	/**
	 * 
	 * @return AuditActionName
	 */
	AuditActionName actionName();

	
	
}
