package com.inn.headstartdemo.security.core.userdetails;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.User;
/**
 *
 * @author Auto Generated By HeadStart
 * @version 1.0
 * Just provide an extra field to add domain
 *
 */
@SuppressWarnings("serial")
public class DomainUser extends User {
	private final String domain;
	
	public String getDomain() {
		return domain;
	}

	public DomainUser(String username,String domain,String password, boolean enabled,
			boolean accountNonExpired, boolean credentialsNonExpired,
			boolean accountNonLocked,
			Collection<? extends GrantedAuthority> authorities) {
		super(username, password, enabled, accountNonExpired, credentialsNonExpired,
				accountNonLocked, authorities);
				this.domain = null;
			}

}
