package com.inn.headstartdemo.model;

import java.io.Serializable;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.annotations.Cascade;
/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="address")
@XmlRootElement(name="Address")
@Audited
 @JsonIgnoreProperties(value={"hibernateLazyInitializer","handler"})
public class Address implements Serializable {
	

	@Basic
	@Column(nullable=false, length=100)
	private String addressLine1;

	@Basic
	@Column(length=100)
	private String addressLine2;

	@Basic
	@Column(length=45)
	private String city;

	@Basic
	@Column(length=45)
	private String country;



	@Id
		     @GeneratedValue(strategy = GenerationType.AUTO)
	 	private Integer id;

	

	@Basic
	@Column(length=250)
	private String landmark;

	@Basic
	@Column(length=45)
	private String latitude;

	@Basic
	@Column(length=45)
	private String longitude;

	@Basic
	@Column(columnDefinition="INT")
	private Integer pincode;

	@Basic
	@Column(length=45)
	private String state;

	@Basic
	@Column(length=10)
	private String street;


	public Address() {
	}

	public Address(Integer id) {
		this.id = id;
	}

	public String getAddressLine1() {
		return addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}



	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLandmark() {
		return landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public Integer getPincode() {
		return pincode;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}
	
	@Override
	public String toString() {
		return "Address [addressLine1=" + addressLine1 + ", addressLine2="
				+ addressLine2 + ", city=" + city + ", country=" + country
				+ ", id=" + id + ", landmark="
				+ landmark + ", latitude=" + latitude + ", longitude="
				+ longitude + ", pincode=" + pincode + ", state=" + state
				+ ", street=" + street + "]";
	}

	@JsonIgnore
	public String getPrimaryKeyIdentifier()
	{
		return ""+getCity();

	}
}
