package com.inn.headstartdemo.model;

import java.util.*;
import javax.persistence.*;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import javax.persistence.NamedQuery;
import javax.persistence.NamedQueries;
/**
 * 
 * @author Autogenerated by Headstart
 * @version 1.0
 *
 */
@NamedQueries(value={@NamedQuery(name="getCommentCountByCustomer", query="select count(c) from Comment c where c.customer= :customer"), @NamedQuery(name="getCommentCountByOffice", query="select count(c) from Comment c where c.office= :office")}) @Entity
@Table(name="comment")
 @JsonIgnoreProperties(value={"hibernateLazyInitializer","handler"})
public class Comment {
	
	@Basic
		private String comment;

	@Basic
	private Date creationtime;

	@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
		private Long id;

	@Basic
	private Date modifiedtime;


		
	@ManyToOne(fetch=FetchType.LAZY)
		@JoinColumn(name="customer_id", columnDefinition="INT UNSIGNED")
		private Customer customer;
	
	
	
		public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
		
	@ManyToOne(fetch=FetchType.LAZY)
		@JoinColumn(name="office_id", columnDefinition="INT UNSIGNED")
		private Office office;
	
	
	
		public Office getOffice() {
		return office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}
		
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
		@JoinColumn(name="createdby", columnDefinition="INT UNSIGNED")
		private Users users;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
		@JoinColumn(name="modifiedby", columnDefinition="INT UNSIGNED")
		private Users users2;


	public Comment() {
	}

	public Comment(Long id) {
		this.id = id;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCreationtime() {
		return creationtime;
	}

	public void setCreationtime(Date creationtime) {
		this.creationtime = creationtime;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getModifiedtime() {
		return modifiedtime;
	}

	public void setModifiedtime(Date modifiedtime) {
		this.modifiedtime = modifiedtime;
	}



	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Users getUsers2() {
		return users2;
	}

	public void setUsers2(Users users2) {
		this.users2 = users2;
	}
}
