package com.inn.headstartdemo.model;

import javax.persistence.*;
import javax.persistence.GeneratedValue;
import com.inn.headstartdemo.utils.BaseEntity;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="customer_attach")
public class CustomerAttach extends BaseEntity {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="customer_id", columnDefinition="INT UNSIGNED", nullable=false)
	private Customer customer;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="attach_id", columnDefinition="INT UNSIGNED", nullable=false)
	private FileUploads fileUploads;

	@Basic
	@Column(length=250)
	private String filename;

	@GeneratedValue(strategy=javax.persistence.GenerationType.AUTO) @Id
	@Column(columnDefinition="INT UNSIGNED")
	private Integer id;


	public CustomerAttach() {
	}

	public CustomerAttach(Integer id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public FileUploads getFileUploads() {
		return fileUploads;
	}

	public void setFileUploads(FileUploads fileUploads) {
		this.fileUploads = fileUploads;
	}

	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
}