package com.inn.headstartdemo.model;

import javax.persistence.*;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.envers.Audited;
/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler"})
@Table(name="file_uploads")
public class FileUploads {
			@Basic
	@Column(columnDefinition="varchar", nullable=false)
	private String file;
			
	@Id
		@GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
	@Column(columnDefinition="INT UNSIGNED")
		private Integer id;

	@Basic
	@Column(length=250)
	private String filename;
	
	public FileUploads() {
	}

	public FileUploads(Integer id) {
		this.id = id;
	}
		public String getFile() {
		return file;
	}

	public void setFile(String file) {
		this.file = file;
	}
		
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@JsonIgnore
	public String getIdentifier()
	{
		return "getId";
	}
	
	public String getFilename() {
		return filename;
	}

	/**
	 * @param filename the filename to set
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

}
