package com.inn.headstartdemo.model;

import javax.persistence.*;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@NamedQueries({@NamedQuery(name="findByFacebookID",query="select u from SocialCredentials u where u.facebookUserid=:facebookId"),
		@NamedQuery(name="findByGoogleID",query="select u from SocialCredentials u where u.googleUserid=:googleId"),
		@NamedQuery(name="findByuserID",query="select u from SocialCredentials u where u.users.userid=:userid")})
@Entity
@Table(name="social_credentials")
  @JsonIgnoreProperties(value={"hibernateLazyInitializer","handler"})
public class SocialCredentials {
	@Basic
	@Column(name="facebook_token", length=250)
	private String facebookToken;

	@Basic
	@Column(name="gmail_token", length=250)
	private String gmailToken;

	@Id
	    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(columnDefinition="INT UNSIGNED")
	 	private Integer id;

	@Basic
	@Column(name="twitter_token", length=250)
	private String twitterToken;
	

	@Basic
	@Column(name="facebook_userid", length=250)
	private String facebookUserid;

	@Basic
	@Column(name="google_userid", length=30)
	private String googleUserid;


	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="userid", columnDefinition="INT UNSIGNED", nullable=false)
	private Users users;
	
	public SocialCredentials() {
	}

	public SocialCredentials(Integer id) {
		this.id = id;
	}

	public String getFacebookToken() {
		return facebookToken;
	}

	public void setFacebookToken(String facebookToken) {
		this.facebookToken = facebookToken;
	}

	public String getGmailToken() {
		return gmailToken;
	}

	public void setGmailToken(String gmailToken) {
		this.gmailToken = gmailToken;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTwitterToken() {
		return twitterToken;
	}

	public void setTwitterToken(String twitterToken) {
		this.twitterToken = twitterToken;
	}

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	

	public String getFacebookUserid() {
		return facebookUserid;
	}

	public void setFacebookUserid(String facebookUserid) {
		this.facebookUserid = facebookUserid;
	}

	public String getGoogleUserid() {
		return googleUserid;
	}

	public void setGoogleUserid(String googleUserid) {
		this.googleUserid = googleUserid;
	}
	}
