package com.inn.headstartdemo.dao.impl;

import java.math.BigInteger;
import java.util.List;


import javax.persistence.Query;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;


import com.inn.headstartdemo.model.Office;
import java.lang.Integer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import com.inn.headstartdemo.dao.annotation.Dao;
import com.inn.headstartdemo.dao.generic.impl.HibernateGenericDao;
import com.inn.headstartdemo.dao.ICommentDao;
import com.inn.headstartdemo.dao.IOfficeDao;
import org.springframework.dao.DataAccessException;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.EmptyResultDataAccessException;
import javax.persistence.NoResultException;
import com.inn.headstartdemo.exceptions.ExceptionHandler;
import com.inn.headstartdemo.exceptions.ValueNotFoundException;


/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
 
/**
 * 
 *Dao 
 * 
 */
@ExceptionHandler @Dao
public class OfficeDaoImpl extends HibernateGenericDao<Integer, Office> implements IOfficeDao {
	
	/** The logger. */
	private Logger logger=LoggerFactory.getLogger(OfficeDaoImpl.class);
	
	
	public OfficeDaoImpl() {
		super(Office.class);
	}

		@Autowired
    private ICommentDao commentDao;
        
	/**
	 * 
	 *Returns the new Office record
	 *@parameter office of type  Office
	 *@returns a new Office
	 * 
	 */
	@ExceptionHandler @Override
	public Office create(@Valid Office office)throws DataAccessException {
	
	logger.info("Create record by an entity :"+office);
	Office newEntity=super.create(office);
	
	return newEntity;
	}

	/**
	 * 
	 *Returns the updated Office record
	 *@parameter anEntity of type  Office
	 *@returns a updated Office record
	 * 
	 */
	@ExceptionHandler @Override
	public Office update(@Valid Office office) throws DataAccessException {
	logger.info("update record by an entity :"+office);
		
		
		return super.update(office);
	}

	/**
	 * 
	 *Method to remove Office record
	 *@parameter office of type  Office
	 * 
	 */
	@ExceptionHandler @Override
	public void delete(@Valid Office office) throws DataAccessException {
	logger.info("Deleting record by an entity :"+office);

		super.delete(office);

	}
	

	/**
	 * 
	 *Method to remove Office record by primary key
	 *@parameter primary key of type Integer  
	 * 
	 */
	@ExceptionHandler @Override
	public void deleteByPk(@NotNull Integer integerPk) throws DataAccessException{
	logger.info("Deleting record by primary key :"+integerPk);
		
		super.deleteByPk(integerPk);

	}
	
	/**
	 * 
	 *Returns the list of Office record 
	 *@returns  Office record
	 * 
	 */
	@ExceptionHandler @Override
	public List<Office> findAll() throws NoResultException,EmptyResultDataAccessException{
		return super.findAll();
	}
	
	/**
	 * 
	 *Returns  the record of Office  finding by primary key 
	 *@parameter primary key  of type Integer
	 *@returns a Office record
	 * 
	 */
	@ExceptionHandler @Override
	public Office findByPk(@NotNull Integer integerPk) throws NoResultException,EmptyResultDataAccessException{
	logger.info("Find record by Primary Key :"+integerPk);
	
		return super.findByPk(integerPk);
	}

	
		
		@ExceptionHandler @Override
	public Long getCommentCountByEntity(@NotNull Integer integerPk) throws ValueNotFoundException{
		logger.info("Finding Entity Comments Counts by office"
				+ integerPk);
		try{
			Office office =  findByPk(integerPk);
			Long count=commentDao.officeCommentCount(office);
			return count;
		}
		catch(Exception e){
		logger.error(e.getMessage());
			 throw new ValueNotFoundException(e.getMessage());
		}
	}
		
		
	@ExceptionHandler public Long getTotalCount(){
			return ((Long)this.getEntityManager().createQuery("select count(x) from Office x  ").getSingleResult());		
		}
}
