package com.inn.headstartdemo.dao.criteria.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.springframework.stereotype.Component;

import com.inn.headstartdemo.dao.annotation.CriteriaExecutor;
import com.inn.headstartdemo.dao.criteria.IQueryExecutor;

/**
 * Hibernate implementation for query execution service. Executes the criteria 
 * generated by {@link HibernateCriteriaBuilder}.
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 * @param <Entity>
 */
@CriteriaExecutor
public class HibernateQueryExecutor<Entity> implements IQueryExecutor<Entity> {
	/**
	 * returns the list of entities filtered after applying criteria.
	 */
	public List<Entity> select(Object criteria) {
		Criteria hibernateCriteria = (Criteria) criteria;
		return hibernateCriteria.list();
	}
	/**
	 * @return int returns the total count of entities filtered using provided criteria.
	 */
	public int count(Object criteria) {
		return	this.select(criteria).size();
	}

}
