package com.inn.headstartdemo.dao.criteria.impl;

import java.util.List;

import com.inn.headstartdemo.dao.annotation.CriteriaExecutor;
import com.inn.headstartdemo.dao.criteria.IQueryExecutor;

/**
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
@CriteriaExecutor
public class JPAQueryExecutor<Entity> implements IQueryExecutor<Entity> {

	/**
	 * 
	 */
	public JPAQueryExecutor() {
		// TODO Auto-generated constructor stub
	}

	public List<Entity> select(Object criteria) {
		// TODO Auto-generated method stub
		return null;
	}

	public int count(Object criteria) {
		// TODO Auto-generated method stub
		return 0;
	}

}
