package com.inn.headstartdemo.dao;

import com.inn.headstartdemo.model.Office;

import com.inn.headstartdemo.dao.generic.IGenericDao;
import java.util.List;
import javax.persistence.NoResultException;
import com.inn.headstartdemo.exceptions.ValueNotFoundException;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IOfficeDao extends IGenericDao<Integer, Office> {

	    Long getCommentCountByEntity(Integer entityPk) throws ValueNotFoundException;
		
		
	public Long getTotalCount();

}
