package com.inn.headstartdemo.dao;

import com.inn.headstartdemo.model.Payment;

import com.inn.headstartdemo.dao.generic.IGenericDao;
import java.util.List;
import javax.persistence.NoResultException;
import com.inn.headstartdemo.exceptions.ValueNotFoundException;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IPaymentDao extends IGenericDao<Long, Payment> {

		
		
	public Long getTotalCount();

}
