package com.inn.headstartdemo.dao;

import com.inn.headstartdemo.dao.generic.IGenericDao;
import com.inn.headstartdemo.model.Permissions;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IPermissionsDao extends IGenericDao<Long, Permissions> {
public Long getTotalCount();
}
