package com.inn.headstartdemo.dao;

import com.inn.headstartdemo.model.Product;

import com.inn.headstartdemo.dao.generic.IGenericDao;
import java.util.List;
import javax.persistence.NoResultException;
import com.inn.headstartdemo.exceptions.ValueNotFoundException;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IProductDao extends IGenericDao<Integer, Product> {

		
		
	public Long getTotalCount();

}
