package com.inn.headstartdemo.dao;

import java.util.List;
import com.inn.headstartdemo.dao.generic.IGenericDao;
import com.inn.headstartdemo.model.Roles;
import com.inn.headstartdemo.exceptions.ValueNotFoundException;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
 
public interface IRolesDao extends IGenericDao<Long, Roles> {

	public List<Roles> getRolesByUserId(Integer userId);
	public Long getTotalCount();
	public List<Roles> getRolesByRolename(String rolename);
}
