package com.inn.headstartdemo.dao;

import java.util.List;
import com.inn.headstartdemo.dao.generic.IGenericDao;
import com.inn.headstartdemo.model.Users;

import com.inn.headstartdemo.utils.BarChart;
import com.inn.headstartdemo.utils.PieChart;
import com.inn.headstartdemo.utils.TrendChart;


/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IUsersDao extends IGenericDao<Integer, Users> {

	public Users findByUserName(String userdetails);
	public Users findByEmail(String emailId);
	public Boolean findByUser(String userdetails);
		public Boolean unLock(String username);	


       	public List<PieChart> getordersorder_statusStatusPieChart();
  	

        	public List<PieChart> getcustomerprioritystatusEnumPieChart();
	   	public List<PieChart> getproductproductlineEnumPieChart();
	  
   	
        	public BarChart getTrendBarChartForemployee() ;
   		
      	public TrendChart getTrendLineChartForpayment(String trendType); 
   	   	}
