package com.inn.headstartdemo.rest.impl;

import java.util.List;
import java.util.Date;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.DELETE;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.QueryParam;
import javax.ws.rs.PathParam;
import javax.ws.rs.core.Context;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.inn.headstartdemo.security.spring.CustomerInfo;
import com.inn.headstartdemo.service.generic.IGenericService;
import com.inn.headstartdemo.rest.generic.AbstractCXFRestService;
import com.inn.headstartdemo.service.ICustomerService;
import com.inn.headstartdemo.model.Customer;
import com.inn.headstartdemo.service.IElasticSearchService;
import com.inn.headstartdemo.rest.ICustomerRest;

import com.inn.headstartdemo.model.Users;
import com.inn.headstartdemo.exceptions.application.BusinessException;
import com.inn.headstartdemo.model.Customer;
import java.lang.Integer;

import com.inn.headstartdemo.exceptions.ExceptionHandler;

import com.inn.headstartdemo.service.IActivityStreamService;
import com.inn.headstartdemo.audit.Auditable;
import com.inn.headstartdemo.audit.AuditActionName;
import com.inn.headstartdemo.audit.AuditActionType;
/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
import javax.validation.Valid;
 
/**
 * 
 * Rest 
 *
 */
 
@ExceptionHandler @Path("/Customer")
@Produces("application/json")
@Consumes("application/json")
@Service("CustomerRestImpl")

public class CustomerRestImpl extends AbstractCXFRestService<Integer, Customer> implements ICustomerRest {
private Logger logger=LoggerFactory.getLogger(CustomerRestImpl.class);
	public CustomerRestImpl() {
		super(Customer.class);
	}
	@Autowired
	private ICustomerService customerService;
	
		@Autowired
	IElasticSearchService elasticSearchService;
	
	
	@Context
	private SearchContext context;

	

		@Autowired
	IActivityStreamService activityservice;
		
	/**
	 * 
	 *Returns the list of all Customer
	 *@returns a list of Customer
	 * 
	 */
	 @ExceptionHandler public List<Customer> findAll()throws BusinessException{
	
	return customerService.findAll();
	
	}

	/**
	 * 
	 *Returns the Customer finding by id
	 *@parameter id of type Integer
	 *@returns a Customer record 
	 * 
	 */	
	 @ExceptionHandler public Customer findById(@QueryParam("") Integer id)throws BusinessException{
		
		logger.info("Find record by id :"+id);
		return customerService.findById(id);
		
		 	}
	
	
	/**
	 * 
	 *Returns the record by searching Customer name
	 *@parameter customer of typeCustomer 
	 *@returns a list of Customer record
	 * 
	 */	
	@ExceptionHandler @GET
	public List<Customer> search(@QueryParam("") Customer customer) throws BusinessException{
		return customerService.search(customer);
	}
	
		
	/**
	 * 
	 *Returns the list of Customer by using lowerlimit and upper limit
	 *@path get path and produce Customer list
	 *@parameter llimit ulimit of type integer in query param
	 *@returns a list of Customer record
	 * 
	 */		
	@ExceptionHandler @GET
	@Path("search")
	@Produces("application/json")
	public List<Customer> search(@QueryParam("llimit") Integer lowerLimit, @QueryParam("ulimit") Integer upperLimit,@QueryParam("orderBy") String orderBy,@QueryParam("orderType") String orderType)throws BusinessException{
			return customerService.searchWithLimitAndOrderBy(context,upperLimit,lowerLimit,orderBy,orderType);
		
	}


	
	/**
	 * 
	 *Returns the new Customer record
	 *@path get path and produce Customer record
	 *@parameter valid Customer entity
	 *@returns a new Customer record
	 * 
	 */	
	@ExceptionHandler @Override
	@POST
	@Path("create")
		@Auditable(actionType=AuditActionType.CREATE,actionName=AuditActionName.CUSTOMER_CREATE)
		public Customer create(@Valid Customer customer) throws BusinessException{
		logger.info("Create record for customer : "+customer);
		Users username =CustomerInfo.getUserInContext();
		
				customer=customerService.create(customer);
		
				
				activityservice.createActivity(username.getFirstname()+" Created a Customer "+customer.getFirstName(), customer.getCustomerNumber().toString(), "Customer");
					
		return customer;
		
	}

	/**
	 * 
	 *Returns the updated Customer record
	 *@path get path and produces updated Customer record
	 *@parameter valid Customer entity
	 *@returns a updated Customer record
	 * 
	 */	
	@ExceptionHandler @Override
	@PUT
	@Path("update")
		@Auditable(actionType=AuditActionType.UPDATE,actionName=AuditActionName.CUSTOMER_UPDATE)
		public Customer update(@Valid Customer customer) throws BusinessException{
	logger.info("Update record for customer : "+customer);
	Users username =CustomerInfo.getUserInContext();
		customer=customerService.update(customer);
				
					activityservice.createActivity(username.getFirstname()+" Updated a Customer "+customer.getFirstName(), customer.getCustomerNumber().toString(), "Customer");
				
				return customer;
		
	}

	/**
	 * 
	 *Returns the removed Customer record
	 *@path get path and delete Customer record 
	 *@parameter valid Customer entity
	 *@returns a removed Customer record
	 * 
	 */	
	@ExceptionHandler @Override
	@Path("delete")
		@Auditable(actionType=AuditActionType.DELETE,actionName=AuditActionName.CUSTOMER_DELETE)
		public boolean remove(Customer customer) throws BusinessException{
	Users username =CustomerInfo.getUserInContext();
	logger.info("Removing record by customer :"+customer);
	customerService.remove(customer);
				
				activityservice.createActivity(username.getFirstname()+" Deleted a Customer "+customer.getFirstName(), customer.getCustomerNumber().toString(), "Customer");
				
			
		return true;
	}

	/**
	 * 
	 *method remove audit action
	 *@path get path to remove audit action
	 *@parameter id of type Integer in path param
	 * 
	 */
	@ExceptionHandler @DELETE
	@Override
	@Path("delete/{id}")
		@Auditable(actionType=AuditActionType.DELETE,actionName=AuditActionName.CUSTOMER_DELETE)
		public void removeById(@PathParam("id") Integer primaryKey) throws BusinessException{
	Users username =CustomerInfo.getUserInContext();
	logger.info("Remove record by primary key :"+primaryKey);
		Customer customer=customerService.findById(primaryKey);
		customerService.removeById(primaryKey);
				
				activityservice.createActivity(username.getFirstname()+" Deleted a Customer "+customer.getFirstName(), customer.getCustomerNumber().toString(), "Customer");
				
			
	}
	
		
	@ExceptionHandler @Override
	public IGenericService<Integer, Customer> getService() {
		return customerService;
	}

	@ExceptionHandler @Override
	public SearchContext getSearchContext() {
		return context;
	}
		
	/**
	 * 
	 *Returns the list of audit action using id 
	 *@path get path to search audit action
	 *@parameter id of type Integer in query param
	 * 
	 */
	@ExceptionHandler @GET
	@Path("auditSearch")
	@Produces("application/json")
	public  String auditSearch(@QueryParam("id") Integer pk)throws BusinessException{
		return customerService.findAudit(pk).toString();
	}
			
		
	@ExceptionHandler @GET
	@Path("totalCount")
	@Produces("application/json")
      public Long getTotalCount(){
				return customerService.getTotalCount();
	}
	
}
