package com.inn.headstartdemo.rest.impl;

import java.util.List;
import java.util.Date;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.DELETE;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.QueryParam;
import javax.ws.rs.PathParam;
import javax.ws.rs.core.Context;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.inn.headstartdemo.security.spring.CustomerInfo;
import com.inn.headstartdemo.service.generic.IGenericService;
import com.inn.headstartdemo.rest.generic.AbstractCXFRestService;
import com.inn.headstartdemo.service.IOrderdetailService;
import com.inn.headstartdemo.model.Orderdetail;
import com.inn.headstartdemo.service.IElasticSearchService;
import com.inn.headstartdemo.rest.IOrderdetailRest;

import com.inn.headstartdemo.model.Users;
import com.inn.headstartdemo.exceptions.application.BusinessException;
import com.inn.headstartdemo.model.Orderdetail;
import java.lang.Integer;

import com.inn.headstartdemo.exceptions.ExceptionHandler;

import com.inn.headstartdemo.service.IActivityStreamService;
import com.inn.headstartdemo.audit.Auditable;
import com.inn.headstartdemo.audit.AuditActionName;
import com.inn.headstartdemo.audit.AuditActionType;
/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
import javax.validation.Valid;
 
/**
 * 
 * Rest 
 *
 */
 
@ExceptionHandler @Path("/Orderdetail")
@Produces("application/json")
@Consumes("application/json")
@Service("OrderdetailRestImpl")

public class OrderdetailRestImpl extends AbstractCXFRestService<Integer, Orderdetail> implements IOrderdetailRest {
private Logger logger=LoggerFactory.getLogger(OrderdetailRestImpl.class);
	public OrderdetailRestImpl() {
		super(Orderdetail.class);
	}
	@Autowired
	private IOrderdetailService orderdetailService;
	
		@Autowired
	IElasticSearchService elasticSearchService;
	
	
	@Context
	private SearchContext context;

	

		@Autowired
	IActivityStreamService activityservice;
		
	/**
	 * 
	 *Returns the list of all Orderdetail
	 *@returns a list of Orderdetail
	 * 
	 */
	 @ExceptionHandler public List<Orderdetail> findAll()throws BusinessException{
	
	return orderdetailService.findAll();
	
	}

	/**
	 * 
	 *Returns the Orderdetail finding by id
	 *@parameter id of type Integer
	 *@returns a Orderdetail record 
	 * 
	 */	
	 @ExceptionHandler public Orderdetail findById(@QueryParam("") Integer id)throws BusinessException{
		
		logger.info("Find record by id :"+id);
		return orderdetailService.findById(id);
		
		 	}
	
	
	/**
	 * 
	 *Returns the record by searching Orderdetail name
	 *@parameter orderdetail of typeOrderdetail 
	 *@returns a list of Orderdetail record
	 * 
	 */	
	@ExceptionHandler @GET
	public List<Orderdetail> search(@QueryParam("") Orderdetail orderdetail) throws BusinessException{
		return orderdetailService.search(orderdetail);
	}
	
		
	/**
	 * 
	 *Returns the list of Orderdetail by using lowerlimit and upper limit
	 *@path get path and produce Orderdetail list
	 *@parameter llimit ulimit of type integer in query param
	 *@returns a list of Orderdetail record
	 * 
	 */		
	@ExceptionHandler @GET
	@Path("search")
	@Produces("application/json")
	public List<Orderdetail> search(@QueryParam("llimit") Integer lowerLimit, @QueryParam("ulimit") Integer upperLimit,@QueryParam("orderBy") String orderBy,@QueryParam("orderType") String orderType)throws BusinessException{
			return orderdetailService.searchWithLimitAndOrderBy(context,upperLimit,lowerLimit,orderBy,orderType);
		
	}


	
	/**
	 * 
	 *Returns the new Orderdetail record
	 *@path get path and produce Orderdetail record
	 *@parameter valid Orderdetail entity
	 *@returns a new Orderdetail record
	 * 
	 */	
	@ExceptionHandler @Override
	@POST
	@Path("create")
		@Auditable(actionType=AuditActionType.CREATE,actionName=AuditActionName.ORDERDETAIL_CREATE)
		public Orderdetail create(@Valid Orderdetail orderdetail) throws BusinessException{
		logger.info("Create record for orderdetail : "+orderdetail);
		Users username =CustomerInfo.getUserInContext();
		
				orderdetail=orderdetailService.create(orderdetail);
		
				
				activityservice.createActivity(username.getFirstname()+" Created a Orderdetail "+orderdetail.getId(), orderdetail.getId().toString(), "Orderdetail");
					
		return orderdetail;
		
	}

	/**
	 * 
	 *Returns the updated Orderdetail record
	 *@path get path and produces updated Orderdetail record
	 *@parameter valid Orderdetail entity
	 *@returns a updated Orderdetail record
	 * 
	 */	
	@ExceptionHandler @Override
	@PUT
	@Path("update")
		@Auditable(actionType=AuditActionType.UPDATE,actionName=AuditActionName.ORDERDETAIL_UPDATE)
		public Orderdetail update(@Valid Orderdetail orderdetail) throws BusinessException{
	logger.info("Update record for orderdetail : "+orderdetail);
	Users username =CustomerInfo.getUserInContext();
		orderdetail=orderdetailService.update(orderdetail);
				
					activityservice.createActivity(username.getFirstname()+" Updated a Orderdetail "+orderdetail.getId(), orderdetail.getId().toString(), "Orderdetail");
				
				return orderdetail;
		
	}

	/**
	 * 
	 *Returns the removed Orderdetail record
	 *@path get path and delete Orderdetail record 
	 *@parameter valid Orderdetail entity
	 *@returns a removed Orderdetail record
	 * 
	 */	
	@ExceptionHandler @Override
	@Path("delete")
		@Auditable(actionType=AuditActionType.DELETE,actionName=AuditActionName.ORDERDETAIL_DELETE)
		public boolean remove(Orderdetail orderdetail) throws BusinessException{
	Users username =CustomerInfo.getUserInContext();
	logger.info("Removing record by orderdetail :"+orderdetail);
	orderdetailService.remove(orderdetail);
				
				activityservice.createActivity(username.getFirstname()+" Deleted a Orderdetail "+orderdetail.getId(), orderdetail.getId().toString(), "Orderdetail");
				
			
		return true;
	}

	/**
	 * 
	 *method remove audit action
	 *@path get path to remove audit action
	 *@parameter id of type Integer in path param
	 * 
	 */
	@ExceptionHandler @DELETE
	@Override
	@Path("delete/{id}")
		@Auditable(actionType=AuditActionType.DELETE,actionName=AuditActionName.ORDERDETAIL_DELETE)
		public void removeById(@PathParam("id") Integer primaryKey) throws BusinessException{
	Users username =CustomerInfo.getUserInContext();
	logger.info("Remove record by primary key :"+primaryKey);
		Orderdetail orderdetail=orderdetailService.findById(primaryKey);
		orderdetailService.removeById(primaryKey);
				
				activityservice.createActivity(username.getFirstname()+" Deleted a Orderdetail "+orderdetail.getId(), orderdetail.getId().toString(), "Orderdetail");
				
			
	}
	
		
	@ExceptionHandler @Override
	public IGenericService<Integer, Orderdetail> getService() {
		return orderdetailService;
	}

	@ExceptionHandler @Override
	public SearchContext getSearchContext() {
		return context;
	}
		
	/**
	 * 
	 *Returns the list of audit action using id 
	 *@path get path to search audit action
	 *@parameter id of type Integer in query param
	 * 
	 */
	@ExceptionHandler @GET
	@Path("auditSearch")
	@Produces("application/json")
	public  String auditSearch(@QueryParam("id") Integer pk)throws BusinessException{
		return orderdetailService.findAudit(pk).toString();
	}
			
		
	@ExceptionHandler @GET
	@Path("totalCount")
	@Produces("application/json")
      public Long getTotalCount(){
				return orderdetailService.getTotalCount();
	}
	
}
