package com.inn.headstartdemo.rest.impl;

import java.util.List;
import java.util.Date;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.DELETE;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.QueryParam;
import javax.ws.rs.PathParam;
import javax.ws.rs.core.Context;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.inn.headstartdemo.security.spring.CustomerInfo;
import com.inn.headstartdemo.service.generic.IGenericService;
import com.inn.headstartdemo.rest.generic.AbstractCXFRestService;
import com.inn.headstartdemo.service.IOrdersService;
import com.inn.headstartdemo.model.Orders;
import com.inn.headstartdemo.service.IElasticSearchService;
import com.inn.headstartdemo.rest.IOrdersRest;

import com.inn.headstartdemo.model.Users;
import com.inn.headstartdemo.exceptions.application.BusinessException;
import com.inn.headstartdemo.model.Orders;
import java.lang.Integer;

import com.inn.headstartdemo.exceptions.ExceptionHandler;

import com.inn.headstartdemo.service.IActivityStreamService;
import com.inn.headstartdemo.audit.Auditable;
import com.inn.headstartdemo.audit.AuditActionName;
import com.inn.headstartdemo.audit.AuditActionType;
/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
import javax.validation.Valid;
 
/**
 * 
 * Rest 
 *
 */
 
@ExceptionHandler @Path("/Orders")
@Produces("application/json")
@Consumes("application/json")
@Service("OrdersRestImpl")

public class OrdersRestImpl extends AbstractCXFRestService<Integer, Orders> implements IOrdersRest {
private Logger logger=LoggerFactory.getLogger(OrdersRestImpl.class);
	public OrdersRestImpl() {
		super(Orders.class);
	}
	@Autowired
	private IOrdersService ordersService;
	
		@Autowired
	IElasticSearchService elasticSearchService;
	
	
	@Context
	private SearchContext context;

	

		@Autowired
	IActivityStreamService activityservice;
		
	/**
	 * 
	 *Returns the list of all Orders
	 *@returns a list of Orders
	 * 
	 */
	 @ExceptionHandler public List<Orders> findAll()throws BusinessException{
	
	return ordersService.findAll();
	
	}

	/**
	 * 
	 *Returns the Orders finding by id
	 *@parameter id of type Integer
	 *@returns a Orders record 
	 * 
	 */	
	 @ExceptionHandler public Orders findById(@QueryParam("") Integer id)throws BusinessException{
		
		logger.info("Find record by id :"+id);
		return ordersService.findById(id);
		
		 	}
	
	
	/**
	 * 
	 *Returns the record by searching Orders name
	 *@parameter orders of typeOrders 
	 *@returns a list of Orders record
	 * 
	 */	
	@ExceptionHandler @GET
	public List<Orders> search(@QueryParam("") Orders orders) throws BusinessException{
		return ordersService.search(orders);
	}
	
		
	/**
	 * 
	 *Returns the list of Orders by using lowerlimit and upper limit
	 *@path get path and produce Orders list
	 *@parameter llimit ulimit of type integer in query param
	 *@returns a list of Orders record
	 * 
	 */		
	@ExceptionHandler @GET
	@Path("search")
	@Produces("application/json")
	public List<Orders> search(@QueryParam("llimit") Integer lowerLimit, @QueryParam("ulimit") Integer upperLimit,@QueryParam("orderBy") String orderBy,@QueryParam("orderType") String orderType)throws BusinessException{
			return ordersService.searchWithLimitAndOrderBy(context,upperLimit,lowerLimit,orderBy,orderType);
		
	}


	
	/**
	 * 
	 *Returns the new Orders record
	 *@path get path and produce Orders record
	 *@parameter valid Orders entity
	 *@returns a new Orders record
	 * 
	 */	
	@ExceptionHandler @Override
	@POST
	@Path("create")
		@Auditable(actionType=AuditActionType.CREATE,actionName=AuditActionName.ORDERS_CREATE)
		public Orders create(@Valid Orders orders) throws BusinessException{
		logger.info("Create record for orders : "+orders);
		Users username =CustomerInfo.getUserInContext();
		
				orders=ordersService.create(orders);
		
				
				activityservice.createActivity(username.getFirstname()+" Created a Orders "+orders.getOrderNumber(), orders.getOrderNumber().toString(), "Orders");
					
		return orders;
		
	}

	/**
	 * 
	 *Returns the updated Orders record
	 *@path get path and produces updated Orders record
	 *@parameter valid Orders entity
	 *@returns a updated Orders record
	 * 
	 */	
	@ExceptionHandler @Override
	@PUT
	@Path("update")
		@Auditable(actionType=AuditActionType.UPDATE,actionName=AuditActionName.ORDERS_UPDATE)
		public Orders update(@Valid Orders orders) throws BusinessException{
	logger.info("Update record for orders : "+orders);
	Users username =CustomerInfo.getUserInContext();
		orders=ordersService.update(orders);
				
					activityservice.createActivity(username.getFirstname()+" Updated a Orders "+orders.getOrderNumber(), orders.getOrderNumber().toString(), "Orders");
				
				return orders;
		
	}

	/**
	 * 
	 *Returns the removed Orders record
	 *@path get path and delete Orders record 
	 *@parameter valid Orders entity
	 *@returns a removed Orders record
	 * 
	 */	
	@ExceptionHandler @Override
	@Path("delete")
		@Auditable(actionType=AuditActionType.DELETE,actionName=AuditActionName.ORDERS_DELETE)
		public boolean remove(Orders orders) throws BusinessException{
	Users username =CustomerInfo.getUserInContext();
	logger.info("Removing record by orders :"+orders);
	ordersService.remove(orders);
				
				activityservice.createActivity(username.getFirstname()+" Deleted a Orders "+orders.getOrderNumber(), orders.getOrderNumber().toString(), "Orders");
				
			
		return true;
	}

	/**
	 * 
	 *method remove audit action
	 *@path get path to remove audit action
	 *@parameter id of type Integer in path param
	 * 
	 */
	@ExceptionHandler @DELETE
	@Override
	@Path("delete/{id}")
		@Auditable(actionType=AuditActionType.DELETE,actionName=AuditActionName.ORDERS_DELETE)
		public void removeById(@PathParam("id") Integer primaryKey) throws BusinessException{
	Users username =CustomerInfo.getUserInContext();
	logger.info("Remove record by primary key :"+primaryKey);
		Orders orders=ordersService.findById(primaryKey);
		ordersService.removeById(primaryKey);
				
				activityservice.createActivity(username.getFirstname()+" Deleted a Orders "+orders.getOrderNumber(), orders.getOrderNumber().toString(), "Orders");
				
			
	}
	
		
	@ExceptionHandler @Override
	public IGenericService<Integer, Orders> getService() {
		return ordersService;
	}

	@ExceptionHandler @Override
	public SearchContext getSearchContext() {
		return context;
	}
		
	/**
	 * 
	 *Returns the list of audit action using id 
	 *@path get path to search audit action
	 *@parameter id of type Integer in query param
	 * 
	 */
	@ExceptionHandler @GET
	@Path("auditSearch")
	@Produces("application/json")
	public  String auditSearch(@QueryParam("id") Integer pk)throws BusinessException{
		return ordersService.findAudit(pk).toString();
	}
			
		
	@ExceptionHandler @GET
	@Path("totalCount")
	@Produces("application/json")
      public Long getTotalCount(){
				return ordersService.getTotalCount();
	}
	
}
