package com.inn.headstartdemo.service;

import com.inn.headstartdemo.model.Users;
import com.inn.headstartdemo.service.generic.IGenericService;
import com.inn.headstartdemo.exceptions.ValueNotFoundException;
import com.inn.headstartdemo.exceptions.application.BusinessException;
import java.io.IOException;
import org.apache.commons.httpclient.HttpException;
import org.json.JSONException;
/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IUsersService extends IGenericService<Integer, Users> {

 	public Boolean unLock(String username);
public Users findByUsername(String name) throws ValueNotFoundException;
public Users findByEmail(String email);
public Users findByUserName(String username);
public Users gmailRegistration(String gaccesstoken ) throws JSONException, BusinessException, HttpException, IOException;
public Users createUsersFromFacebook(String userID,String facebookToken ) throws JSONException, HttpException, IOException,BusinessException,ValueNotFoundException;
public void setUserAuthentication(Users newsc) throws BusinessException;
}
