package com.inn.headstartdemo.dao.criteria;

import com.inn.headstartdemo.utils.QueryObject;

/**
 * Represents the criteria builder interface. Implementing class shall be 
 * responsible for generating criteria for the provided query object based
 * upon the underlying technology. 
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IQueryCriteriaBuilder<Entity> {
	/**
	 * converts the query object into a query.
	 * @param queryObject
	 * @param entityClass
	 * @return
	 */
	Object buildCriteria(QueryObject queryObject, Class<Entity> entityClass);
}
