package com.inn.headstartdemo.rest;

import java.util.List;

import javax.ws.rs.QueryParam;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

import com.inn.headstartdemo.model.Customer;
import java.lang.Integer;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface ICustomerRest {
	/*public List<Customer> findAll();	
	public Customer findById(@QueryParam("") Integer id);	
	public List<Customer> search(@QueryParam("") Customer student);
	public List<Customer> search(SearchContext qo);
	 public Long getTotalCount();
	*/


}
