package com.inn.headstartdemo.rest;

import java.util.List;

import javax.ws.rs.QueryParam;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

import com.inn.headstartdemo.model.Office;
import java.lang.Integer;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IOfficeRest {
	/*public List<Office> findAll();	
	public Office findById(@QueryParam("") Integer id);	
	public List<Office> search(@QueryParam("") Office student);
	public List<Office> search(SearchContext qo);
	 public Long getTotalCount();
	*/


}
