package com.inn.headstartdemo.rest;

import java.util.List;

import javax.ws.rs.QueryParam;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

import com.inn.headstartdemo.model.Permissions;

import java.lang.Long;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IPermissionsRest {
	public List<Permissions> findAll();	
	public Permissions findById(@QueryParam("") Long id);	
	public List<Permissions> search(@QueryParam("") Permissions student);
	public List<Permissions> search(SearchContext qo);
}
