package com.inn.headstartdemo.rest;

import java.util.List;

import javax.ws.rs.QueryParam;

import org.apache.cxf.jaxrs.ext.search.SearchContext;

import com.inn.headstartdemo.model.Product;
import java.lang.Integer;

/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
public interface IProductRest {
	/*public List<Product> findAll();	
	public Product findById(@QueryParam("") Integer id);	
	public List<Product> search(@QueryParam("") Product student);
	public List<Product> search(SearchContext qo);
	 public Long getTotalCount();
	*/


}
