package com.inn.headstartdemo.service.impl;

import java.util.List;

import javax.persistence.NoResultException;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.elasticsearch.index.engine.DocumentMissingException;
import org.hibernate.exception.ConstraintViolationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.inn.headstartdemo.dao.IEmployeeDao;
import com.inn.headstartdemo.exceptions.ExceptionHandler;
import com.inn.headstartdemo.exceptions.application.BusinessException;
import com.inn.headstartdemo.exceptions.application.EmployeeAlreadyExistException;
import com.inn.headstartdemo.exceptions.application.EmployeeNotFoundException;
import com.inn.headstartdemo.exceptions.application.ValidationFailedException;
import com.inn.headstartdemo.model.Employee;
import com.inn.headstartdemo.model.Users;
import com.inn.headstartdemo.security.spring.CustomerInfo;
import com.inn.headstartdemo.service.IElasticSearchService;
import com.inn.headstartdemo.service.IEmployeeService;
import com.inn.headstartdemo.service.generic.AbstractService;



/**
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 */
 
/**
 * 
 * Service 
 *
 */
 
@ExceptionHandler @Service
@Transactional
public class EmployeeServiceImpl extends AbstractService<Integer, Employee> implements IEmployeeService {
 private Logger logger=LoggerFactory.getLogger(EmployeeServiceImpl.class);
 private  IEmployeeDao employeeDao;
	@ExceptionHandler @Autowired
	public void setDao(IEmployeeDao dao) {
		super.setDao(dao);
		employeeDao = dao;
	}
	 /** IElasticSearchService Bean injection */
	@Autowired
	IElasticSearchService elasticSearchService;
	
		/**
	 * 
	 *Returns the list of Employee using entity
	 *@parameter employee to search record
	 *@returns a Employee record
	 * 
	 */
	@ExceptionHandler @Override
	public List<Employee> search(Employee employee) throws BusinessException{
	logger.info("Finding record by employee name :"+employee);
		return super.search(employee);
	}

	/**
	 * 
	 *Returns the Employee finding by id
	 *@parameter primaryKey to find Employee
	 *@throws BusinessException
	 *@throws EmployeeNotFoundException
	 *@returns a Employee record
	 * 
	 */
	@ExceptionHandler @Override
	public Employee findById(@NotNull Integer primaryKey)throws EmployeeNotFoundException,BusinessException{
		logger.info("Finding record by primaryKey :"+primaryKey);
		try{
		return (super.findById(primaryKey));
		}
		catch(EmptyResultDataAccessException ex)
		{
			throw new EmployeeNotFoundException(ex);
		}catch(NoResultException ex)
		{
			throw new EmployeeNotFoundException(ex);
		}
	}

	/**
	 * 
	 *Returns the list of Employee 
	 *@throws BusinessException
	 *@throws EmployeeNotFoundException
	 *@returns a list of Employee record
	 * 
	 */
	@ExceptionHandler @Override
	public List<Employee> findAll() throws BusinessException ,EmployeeNotFoundException{
		try{
			return super.findAll();

		}
		catch(EmptyResultDataAccessException ex)
		{	
			throw new EmployeeNotFoundException(ex);
		}catch(NoResultException ex)
		{
			throw new EmployeeNotFoundException(ex);
		}
	}

	/**
	 * 
	 *Returns the new valid Employee record
	 *@parameter employee to create new record
	 *@returns a new Employee record
	 *@throws BusinessException 
	 *@throws EmployeeAlreadyExistException 
	 *@throws ValidationFailedException		
	 */
	@ExceptionHandler @Override
	public Employee create(@Valid Employee employee) throws BusinessException{
    logger.info("Create record by employee : "+employee);
		try{	
    	Users username =CustomerInfo.getUserInContext();
			
	Employee newEntity=super.create(employee);
	
						

		
		elasticSearchService.createIndex(newEntity.getEmployeeNumber().toString(),newEntity.getFirstName().toString(),"Employee");
		
	return newEntity;
    	
    	}catch(DataIntegrityViolationException ex)
    	{
				throw new EmployeeAlreadyExistException(ex);
    		
    		
    	}catch(ConstraintViolationException  ex){
    		
    	throw new ValidationFailedException(ex);
    	}
	}

	/**
	 * 
	 *Returns the updated valid Employee record
	 *@parameter employee to update Employee record
	 * @throws BusinessException	
 	 * @throws ValidationFailedException	
 	 * @throws EmployeeAlreadyExistException	
	 *@returns a updated Employee record
	 * 
	 */
	@ExceptionHandler @Override
	public Employee update(@Valid Employee employee)throws BusinessException {
	logger.info("Update record by employee : "+employee);	
		try{
			Users username =CustomerInfo.getUserInContext();		
			
			
			Employee newEntity= super.update(employee);
						
			try{
			 	elasticSearchService.updateDocument("Employee", employee.getEmployeeNumber().toString(),"",employee.getFirstName().toString());
			}
			catch(DocumentMissingException ex)
			{
					logger.error(ex.getMessage());
				elasticSearchService.createIndex( employee.getEmployeeNumber().toString(),employee.getFirstName().toString(),"Employee");
			}
			catch(NullPointerException e)
			{
				logger.error(e.getMessage());
			  elasticSearchService.createIndex( employee.getEmployeeNumber().toString(),employee.getFirstName().toString(),"Employee");
			}
				return newEntity;
		
		}catch(DataIntegrityViolationException ex)
    	{
			throw new EmployeeAlreadyExistException(ex);
    		
    		
    	}catch(ConstraintViolationException  ex){
    		
    		throw new ValidationFailedException(ex);
    	}
	}

	/**
	 * 
	 *method to remove Employee record
	 * @throws 	BusinessException
	 *@parameter employee  to remove Employee record
	 * 
	 */
	@ExceptionHandler @Override
	public void remove(Employee employee) throws BusinessException {
	logger.info("Remove record by employee : "+employee);	
		try{
			super.remove(employee);
		}catch(DataIntegrityViolationException ex)
    	{
    		throw new ValidationFailedException(ex);
    		
    	}catch(ConstraintViolationException ex)
		{
			throw new EmployeeAlreadyExistException(ex);
		}
				elasticSearchService.deleteDocument("Employee", employee.getEmployeeNumber().toString());
			}

	/**
	 * 
	 *method to remove Employee record by primaryKey
	 *@throws BusinessException 	
	 *@parameter primaryKey  to remove Employee 
	 * 
	 */
	@ExceptionHandler @Override
	public void removeById(@NotNull Integer primaryKey) throws BusinessException  {
	logger.info("Remove record by primaryKey :"+primaryKey);
	try{	
			
						Employee employee = employeeDao.findByPk(primaryKey);
						employee.setOffice(null);
						super.remove(employee);
					}catch(DataIntegrityViolationException ex)
    	{
    		throw new ValidationFailedException(ex);
    		
    	}catch(ConstraintViolationException ex)
		{
			throw new EmployeeAlreadyExistException(ex);
		}
	  		elasticSearchService.deleteDocument("Employee", primaryKey.toString());
			}
	

  @ExceptionHandler public Long getTotalCount(){
				return employeeDao.getTotalCount();
	}


}
