package com.inn.headstartdemo.service.generic;

import java.util.List;

import com.inn.headstartdemo.utils.AdvanceSearchResult;
import com.inn.headstartdemo.utils.QueryObject;
import org.json.JSONObject;
import org.springframework.transaction.annotation.Transactional;
import  com.inn.headstartdemo.exceptions.application.BusinessException;


import org.apache.cxf.jaxrs.ext.search.SearchContext;

/**
 * Generic service interface.
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 *
 * @param <Pk> represents the primary key of the entity.
 * @param <Entity> represents the entity type.
 */
 @Transactional
public interface IGenericService<Pk, Entity> {
	/**
	 * @return returns the filtered entities after performing advance search.
	 * 
	 * @param queryObject represents the query.
	 */
	AdvanceSearchResult<Entity> advanceSearch(QueryObject queryObject);
	/**
	 * API which performs a search based on the values in the entity. All the
	 * values provided in the entity are compared using equal operator. 
	 * This doesn't support regular expression based search.
	 * 
	 * @param entity represents the entity instance.
	 * 
	 * @return returns the list of entities filtered after performing search.
	 */
	List<Entity> search(Entity entity)throws BusinessException;
	/**
	 * searches the entity based on the primary key.
	 * 
	 * @param primaryKey represents the primary key of the entity.
	 * 
	 * @return returns the entity found in the persistence store.
	 */
	Entity findById(Pk primaryKey)throws BusinessException;
	/**
	 * @return returns all the entities stored in the persistence store.
	 */
	List<Entity> findAll()throws BusinessException;
	/**
	 * creates the provided entity.
	 * 
	 * @param anEntity entity to create.
	 */
	Entity create(Entity anEntity)throws BusinessException;
	/**
	 * updates the provided entity.
	 * 
	 * @param anEntity entity to update.
	 */
	Entity update(Entity anEntity)throws BusinessException;
	/**
	 * removes the entity, note: primary key must be set within the
	 * entity.
	 * 
	 * @param anEntity
	 */
	void remove(Entity anEntity)throws BusinessException;
	/**
	 * removes the entity identified by the provided primary key.
	 * @param primaryKey
	 */
	void removeById(Pk primaryKey)throws BusinessException;
	
	/**
	 * search on entity with FIQL latest
	 * @param context,maxLimit,Minlimit
	 */
	List<Entity> searchWithLimit(SearchContext context,Integer maxLimit,Integer minLimit )throws BusinessException;
	
	
	/**
	 * search on entity with FIQL latest
	 * @param context,maxLimit,Minlimit,orderby,orderType
	 */
	 List<Entity> searchWithLimitAndOrderBy(SearchContext ctx ,Integer maxLimit,Integer minLimit,String orderby,String orderType )throws BusinessException;
	
		/**
	 * search on entity History 
	 * @param PrimaryKey
	 */
	List<JSONObject> findAudit(Pk pk)throws BusinessException;
	
}
